import 'package:my_portfolio/helpers/project_class.dart';

final projectHistory = [
  Project(
    'An Android/iOS Application which contains a lot of Food Recipies from all over the world.',
    'Indian Rasoi',
    true,
    true,
    'www.google.com',
    'Github link',
    ['Flutter'],
  ),
  Project(
    'An Android/iOS Application which contains a lot of Food Recipies from all over the world.',
    'Indian Rasoi',
    false,
    true,
    '',
    'Github link',
    ['Flutter'],
  ),
  Project(
    'An Android/iOS Application which contains a lot of Food Recipies from all over the world.',
    'Indian Rasoi',
    false,
    true,
    '',
    'Github link',
    ['Flutter'],
  ),
  Project(
    'An Android/iOS Application which contains a lot of Food Recipies from all over the world.',
    'Indian Rasoi',
    false,
    true,
    '',
    'Github link',
    ['Flutter'],
  ),
  Project(
    'An Android/iOS Application which contains a lot of Food Recipies from all over the world.',
    'Indian Rasoi',
    false,
    true,
    '',
    'Github link',
    ['Flutter'],
  ),
  Project(
    'An Android/iOS Application which contains a lot of Food Recipies from all over the world.',
    'Indian Rasoi',
    false,
    true,
    '',
    'Github link',
    ['Flutter'],
  ),
  Project(
    'An Android/iOS Application which contains a lot of Food Recipies from all over the world.',
    'Indian Rasoi',
    false,
    true,
    '',
    'Github link',
    ['Flutter'],
  ),
  Project(
    'An Android/iOS Application which contains a lot of Food Recipies from all over the world.',
    'Indian Rasoi',
    false,
    true,
    '',
    'Github link',
    ['Flutter'],
  ),
  Project(
    'An Android/iOS Application which contains a lot of Food Recipies from all over the world.',
    'Indian Rasoi',
    false,
    true,
    '',
    'Github link',
    ['Flutter'],
  ),
  Project(
    'An Android/iOS Application which contains a lot of Food Recipies from all over the world.',
    'Indian Rasoi',
    false,
    true,
    '',
    'Github link',
    ['Flutter'],
  ),
  Project(
    'An Android/iOS Application which contains a lot of Food Recipies from all over the world.',
    'Indian Rasoi',
    false,
    true,
    '',
    'Github link',
    ['Flutter'],
  ),
  Project(
    'An Android/iOS Application which contains a lot of Food Recipies from all over the world.',
    'Indian Rasoi',
    false,
    true,
    '',
    'Github link',
    ['Flutter'],
  ),
  Project(
    'An Android/iOS Application which contains a lot of Food Recipies from all over the world.',
    'Indian Rasoi',
    false,
    true,
    '',
    'Github link',
    ['Flutter'],
  ),
  Project(
    'An Android/iOS Application which contains a lot of Food Recipies from all over the world.',
    'Indian Rasoi',
    false,
    true,
    '',
    'Github link',
    ['Flutter'],
  ),
  Project(
    'An Android/iOS Application which contains a lot of Food Recipies from all over the world.',
    'Indian Rasoi',
    false,
    true,
    '',
    'Github link',
    ['Flutter'],
  ),
];
