import 'package:my_portfolio/helpers/project_class.dart';

final projectHistory = [
  Project(
    'An Android and iOS chatting app developed using Flutter and Firebase. Its uses concept of Morse code for encrypting and decrypting the message. It also have an Option of communication using the torch of Mobile.',
    'MorseChatterApp',
    false,
    true,
    '',
    'https://github.com/chirag-goel360/MorseChatterApp',
    ['Flutter', 'Firebase'],
  ),
  Project(
    'An Android/iOS Application designed for Food Lovers. It contains a lot of recipies of all over the world. It also tells approximate value of how many calories, carbohydrates, fats and protien are present in the food.',
    'IndianRasoi',
    false,
    true,
    '',
    'https://github.com/chirag-goel360/IndianRasoi',
    ['Flutter', 'Dart', 'Firebase'],
  ),
  Project(
    'A website designed using Django, SQL where you can post your question and can give answer to specific questions. Your answer can be reviewed, upvoted and you can know how relevant your answer will be for others.',
    'Online-Q-A-System',
    false,
    true,
    '',
    'https://github.com/chirag-goel360/Online-Q-A-System',
    ['Django', 'HTML', 'CSS', 'Python', 'SQL'],
  ),
  Project(
    'An Android, iOS and Web application developed using flutter, python and tensorflow model to convert a human made sketch of person, shoes and handbag into real Images.',
    'SketchToImageGenerator',
    true,
    true,
    'https://sketchtoimage.netlify.app/',
    'https://github.com/chirag-goel360/SketchToImageGenerator',
    ['Flutter', 'Dart', 'Python', 'Tflite', 'Flask'],
  ),
  Project(
    'My portfolio designed using Flutter for Android, iOS and Web. It contains brief information about my career and education.',
    'MyPortFolio',
    true,
    true,
    'https://portfoliochirag.netlify.app/',
    'https://github.com/chirag-goel360/MyPortFolio',
    ['Flutter', 'Dart'],
  ),
  Project(
    'An Android and iOS application to detect whether a person is wearing a mask or not. It detect mask using tflite model.',
    'face_mask_detector',
    false,
    true,
    '',
    'https://github.com/chirag-goel360/face_mask_detector',
    ['Flutter', 'Dart', 'Tflite', 'Python'],
  ),
  Project(
    'Clock application using flutter for Android and iOS. It has time zones, digital clock, alarms, timer, stopwatch all integrated into a single application.',
    'Flutter_Clock',
    false,
    true,
    '',
    'https://github.com/chirag-goel360/Flutter_Clock',
    ['Flutter'],
  ),
  Project(
    'A web Application designed using C# and SQL Server for performing CRUD operation of a Zoo.',
    'Zoo_Management',
    false,
    true,
    '',
    'https://github.com/chirag-goel360/Zoo_Management',
    ['C#', 'SQL Server'],
  ),
  Project(
    'An Artificial Intelligence based website using Streamlit that is used to classify the items into categories using OpenAI API.',
    'OpenAI_ItemClassifier',
    false,
    true,
    '',
    'https://github.com/chirag-goel360/OpenAI_ItemClassifier',
    ['Python', 'OpenAI', 'Streamlit'],
  ),
  Project(
    'NewsBook is a flutter Android and iOS application which uses an API to fetch the news according to categories which a user selects.',
    'NewsBook',
    false,
    true,
    '',
    'https://github.com/chirag-goel360/NewsBook',
    ['Flutter', 'API', 'Dart'],
  ),
  Project(
    'A fruits and vegetables classifier. It can detect 131 different variety of fruits and vegetables available in the market. Classification is done using Tflite model.',
    'fruit_vege_detector',
    false,
    true,
    '',
    'https://github.com/chirag-goel360/fruit_vege_detector',
    ['Flutter', 'Tflite', 'Python'],
  ),
  Project(
    'A dog breed detector is an Android and iOS application developed using flutter and tensorflow lite model to detect the breed of dog.',
    'dog_breed_detector',
    false,
    true,
    '',
    'https://github.com/chirag-goel360/dog_breed_detector',
    ['Flutter', 'Tflite', 'Python'],
  ),
  Project(
    'A dino game is developed using flutter and flame engine for Android and iOS. Dino game is similar to Chrome dino game but with better graphics.',
    'dino_game',
    false,
    true,
    '',
    'https://github.com/chirag-goel360/dino_game',
    ['Flutter', 'Flame'],
  ),
  Project(
    'An Android/iOS Application which is used to generate caption for an image using API of Redhat.',
    'Caption_Generator',
    false,
    true,
    '',
    'https://github.com/chirag-goel360/Caption_Generator',
    ['Flutter', 'kubernetes', 'API'],
  ),
  Project(
    'A wallpaper application using Flutter for Android and iOS. In application Wallpapers are fetched with the help of API according to different categories.',
    'WallpaperApp',
    false,
    true,
    '',
    'https://github.com/chirag-goel360/WallpaperApp',
    ['Flutter', 'API', 'Dart'],
  ),
  Project(
    'A simple currency convertor developed using flutter. It can convert almost all of the currencies of world to other.',
    'Currency_Convertor',
    false,
    true,
    '',
    'https://github.com/chirag-goel360/Currency_Convertor',
    ['Flutter', 'Dart'],
  ),
  Project(
    'A weather Application for Android and iOS to learn BLOC pattern in flutter.',
    'WeatherApp_BLOC',
    false,
    true,
    '',
    'https://github.com/chirag-goel360/WeatherApp_BLOC',
    ['Flutter', 'Dart'],
  ),
  Project(
    'A ToDo Android/iOS Application using Flutter to perform Task Creation',
    'Todo_Flutter',
    false,
    true,
    '',
    'https://github.com/chirag-goel360/Todo_Flutter',
    ['Flutter', 'Dart'],
  ),
  Project(
    'A simple C# application with is used to unscramble the words from scrambled word on the basis of a dictionary of words.',
    'WordUnscrambler',
    false,
    true,
    '',
    'https://github.com/chirag-goel360/WordUnscrambler',
    ['C#'],
  ),
  Project(
    'A normal employee page in flutter to learn BLOC pattern in flutter. BLOC is used to increment and decrement salary of employee in this Project.',
    'Learning-bloc-Flutter',
    false,
    true,
    '',
    'https://github.com/chirag-goel360/Learning-bloc-Flutter',
    ['Flutter', 'Dart'],
  ),
  Project(
    'A cat breed detector is an Android and iOS application developed using flutter and tensorflow lite model to determine the breed of the cat.',
    'cat_breed_detector',
    false,
    true,
    '',
    'https://github.com/chirag-goel360/cat_breed_detector',
    ['Flutter', 'Tflite', 'Python'],
  ),
  Project(
    'An Android/iOS Application which is used to detect the faces in the picture. It only detects the faces. It can not describes whose face is it.',
    'face_detection',
    false,
    true,
    '',
    'https://github.com/chirag-goel360/face_detection',
    ['Flutter', 'Tflite', 'Python'],
  ),
  Project(
    'An Android/iOS Application which recognise the text present in the picture.',
    'text_recognition',
    false,
    true,
    '',
    'https://github.com/chirag-goel360/text_recognition',
    ['Flutter', 'Dart'],
  ),
  Project(
    'An Android/iOS Application which is used to scan the barcodes or qrcodes.',
    'barcode_reader',
    false,
    true,
    '',
    'https://github.com/chirag-goel360/barcode_reader',
    ['Flutter', 'Dart'],
  ),
  Project(
    'An Android/iOS Application which is used to label the images on the basis of tensorflow Model.',
    'Image_Labeling',
    false,
    true,
    '',
    'https://github.com/chirag-goel360/Image_Labeling',
    ['Flutter', 'Tflite'],
  ),
  Project(
    'A giphy Search engine designed using flutter. Giphy API is used for the searching purpose.',
    'Giphy_GIFs',
    false,
    true,
    '',
    'https://github.com/chirag-goel360/Giphy_GIFs',
    ['Flutter', 'Dart', 'API'],
  ),
  Project(
    'An Android and iOS application that is use to convert voice to text in flutter.',
    'flutter_voice',
    false,
    true,
    '',
    'https://github.com/chirag-goel360/flutter_voice',
    ['Flutter'],
  ),
  Project(
    'A flower detector which can detect a small amount of flowers only. The application is designed using flutter for Android and iOS.',
    'flower_detector',
    false,
    true,
    '',
    'https://github.com/chirag-goel360/flower_detector',
    ['Flutter', 'Tflite', 'Python'],
  ),
  Project(
    'A flutter Android and iOS application which is used to detect a cat and dog in images.',
    'cat_vs_dog',
    false,
    true,
    '',
    'https://github.com/chirag-goel360/cat_vs_dog',
    ['Flutter', 'Tflite'],
  ),
  Project(
    'Razorpay Integration in flutter. Application works in Android as well as iOS.',
    'RazorPay_Demonstration',
    false,
    true,
    '',
    'https://github.com/chirag-goel360/RazorPay_Demonstration',
    ['Flutter'],
  ),
  Project(
    'A barcode and qrcode scanner as well as generator developed using the flutter framework. It works for android as well as iOS.',
    'Scanner',
    false,
    true,
    '',
    'https://github.com/chirag-goel360/Scanner',
    ['Flutter'],
  ),
  Project(
    'DrawBoard is a normal drawing board for Android and iOS using flutter. It has feature of changing the width of Brush, changing color of brush, an eraser and to save the drawing.',
    'DrawBoard',
    false,
    true,
    '',
    'https://github.com/chirag-goel360/DrawBoard',
    ['Flutter', 'Dart'],
  ),
  Project(
    'A Cafe Menu UI designed using Flutter for Android and iOS.',
    'CafeMenu',
    false,
    true,
    '',
    'https://github.com/chirag-goel360/CafeMenu',
    ['Flutter'],
  ),
  Project(
    'An online radio Application for Android and iOS developed using flutter. It also has Alan AI for Voice Assistant.',
    'AI_Radio',
    false,
    true,
    '',
    'https://github.com/chirag-goel360/AI_Radio',
    ['Flutter', 'Alan API'],
  ),
  Project(
    'A translator which converts words into emoji. The Application works on Android, iOS as well as Website and is developed with the help of Flutter.',
    'emoji_transalator',
    false,
    true,
    '',
    'https://github.com/chirag-goel360/emoji_transalator',
    ['Flutter', 'Dart'],
  ),
  Project(
    'A hangman game developed using Python. In game different words are taken with the help of Python Library.',
    'Hangman',
    false,
    true,
    '',
    'https://github.com/chirag-goel360/Hangman',
    ['Python', 'Pygame'],
  ),
  Project(
    'A website developed using ReactJs which let you to see different wallpapers using an API.',
    'Image-Gallery-React',
    false,
    true,
    '',
    'https://github.com/chirag-goel360/Image-Gallery-React',
    ['ReactJs', 'JavaScript', 'API'],
  ),
  Project(
    'An Android and iOS Application developed using flutter which helps to learn different algorithms in different languages.',
    'Algorithm_App',
    false,
    true,
    '',
    'https://github.com/chirag-goel360/Algorithm_App',
    ['Flutter', 'JSON'],
  ),
  Project(
    'Morse Code Generator is an Appllication which is used to Generate Morse code using blinking of eyes.',
    'MorseCodeGenerator',
    false,
    true,
    '',
    'https://github.com/chirag-goel360/MorseCodeGenerator',
    ['Python', 'OpenCV'],
  ),
  Project(
    'A Dictionary Android and iOS Application developed using Flutter. It is used to Search words with the help of API',
    'Dictionary',
    false,
    true,
    '',
    'https://github.com/chirag-goel360/Dictionary',
    ['Flutter', 'API'],
  ),
  Project(
    'A Simple BMI Calculator for Android and iOS using Flutter.',
    'BMI_Calculator',
    false,
    true,
    '',
    'https://github.com/chirag-goel360/BMI_Calculator',
    ['Flutter'],
  ),
  Project(
    'A torrent Scrapper using Python. You just have to write the things you want in notepad file and it will auto find them from different torrent sites.',
    'TorrentDownloader',
    false,
    true,
    '',
    'https://github.com/chirag-goel360/TorrentDownloader',
    ['Python'],
  ),
  Project(
    'A simple calculator developed using Flutter for Android and iOS.',
    'Calculator',
    false,
    true,
    '',
    'https://github.com/chirag-goel360/Calculator',
    ['Flutter', 'Dart'],
  ),
  Project(
    'A pokedex developed using Flutter for Android, iOS and Web. Its contains all the information about a Pokemon.',
    'Pokemon_Pokedex',
    true,
    true,
    'https://pokemon-pokedex-web.netlify.app/',
    'https://github.com/chirag-goel360/Pokemon_Pokedex',
    ['Flutter', 'API'],
  ),
  Project(
    'A voice assistant which performs various tasks based on user\'s voice instructions. This bot provides the facilities to control computer using voice instructions i.e. no need of user to work on keyboard even to write an email.',
    'JarvisBot',
    false,
    true,
    '',
    'https://github.com/chirag-goel360/JarvisBot',
    ['Python'],
  ),
  Project(
    'My visit Card designed using Flutter for Android, iOS and Websites.',
    'Visit_Card_Web_App',
    false,
    true,
    '',
    'https://github.com/chirag-goel360/Visit_Card_Web_App',
    ['Flutter'],
  ),
  Project(
    'A website, Android and iOS Application developed using Flutter. Its only UI for a camp fire or piknik site.',
    'Camp_Fire_Web_App_UI',
    false,
    true,
    '',
    'https://github.com/chirag-goel360/Camp_Fire_Web_App_UI',
    ['Flutter'],
  ),
  Project(
    'A christmas tree developed using Flutter for Android, iOS and Web.',
    'Christmas_Tree',
    false,
    true,
    '',
    'https://github.com/chirag-goel360/Christmas_Tree',
    ['Flutter'],
  ),
  Project(
    'A tic-tac-toe game developed using C#. It is a console Application.',
    'Tic_Tac_Toe',
    false,
    true,
    '',
    'https://github.com/chirag-goel360/Tic_Tac_Toe',
    ['C#'],
  ),
  Project(
    'An Expense Tracker developed using ReactJs.',
    'Expense-Tracker-React',
    false,
    true,
    '',
    'https://github.com/chirag-goel360/Expense-Tracker-React',
    ['ReactJs', 'JavaScript'],
  ),
  Project(
    'An Open port finder for a Website using Python.',
    'Open-Port-Finder',
    false,
    true,
    '',
    'https://github.com/chirag-goel360/Open-Port-Finder',
    ['Python'],
  ),
  Project(
    'A weather Application for Android and iOS using Flutter.',
    'WeatherApp',
    false,
    true,
    '',
    'https://github.com/chirag-goel360/WeatherApp',
    ['Flutter', 'API'],
  ),
  Project(
    'A whiteboard using Flutter for Android and iOS.',
    'WhiteBoard',
    false,
    true,
    '',
    'https://github.com/chirag-goel360/WhiteBoard',
    ['Flutter'],
  ),
  Project(
    'An Android and iOS Application through Flutter for Snapchat filters. Snapchat filters are occupied using API.',
    'Snappy',
    false,
    true,
    '',
    'https://github.com/chirag-goel360/Snappy',
    ['Flutter', 'API'],
  ),
  Project(
    'A repository in which I keep my Flutter UI codes.',
    'Flutter-UI',
    false,
    true,
    '',
    'https://github.com/chirag-goel360/Flutter-UI',
    ['Flutter'],
  ),
  Project(
    'Android and iOS Application for Interview Question using Flutter and JSON.',
    'Final_Interview_App',
    false,
    true,
    '',
    'https://github.com/chirag-goel360/Final_Interview_App',
    ['Flutter', 'JSON'],
  ),
];
