import 'package:my_portfolio/helpers/certificate/certification_class.dart';

final certificationHistory = [
  Certification(
    'October 2020',
    'Code Warriors',
    '30 Days of Flutter',
    true,
    'https://verify.givemycertificate.com/verify/2010009711000138',
    'assets/Organisations/code-warriors.jpg',
  ),
  Certification(
    'July 2021',
    'Microsoft',
    'Azure Data Fundamentals',
    true,
    'https://www.credly.com/badges/a4c0f610-70f6-424f-a0a2-b71144684a30/public_url',
    'assets/Organisations/microsoft.png',
  ),
  Certification(
    'June 2021',
    'ICDAM',
    'Encrypted Morse Communication using Eye Blinks and Light Bulb',
    true,
    'https://drive.google.com/file/d/1Ajs5721xEslufawUaLUY2rBJLusiUySM/view?usp=sharing',
    'assets/Organisations/icdam.png',
  ),
  Certification(
    'September 2021',
    'Udemy',
    'The Complete Digital Marketing Course - 12 Courses in 1',
    true,
    'https://www.udemy.com/certificate/UC-c969e7c8-a3f6-4c32-b01e-c3fcf8b8e45e/',
    'assets/Organisations/udemy.png',
  ),
  Certification(
    'October 2020',
    'HackerRank',
    'Python (Basic)',
    true,
    'https://www.hackerrank.com/certificates/42F368F66372',
    'assets/Organisations/hackerrank.jpg',
  ),
  Certification(
    'July 2020',
    'udemy',
    'Python for Beginners',
    true,
    'https://www.udemy.com/certificate/UC-34946dbb-50d1-4ffa-b6ad-76b6f28eb355/',
    'assets/Organisations/udemy.png',
  ),
  Certification(
    'October 2020',
    'HackerRank',
    'Java (Basic)',
    true,
    'https://www.hackerrank.com/certificates/F88E09BE8EB5',
    'assets/Organisations/hackerrank.jpg',
  ),
  Certification(
    'July 2020',
    'Utkarshini Edutech',
    'Networking Protocols',
    true,
    'https://drive.google.com/file/d/1nzejn7THe6VHlojTlLaLRE5dTFrtMBpe/view?usp=sharing',
    'assets/Organisations/utkarshini.jpg',
  ),
  Certification(
    'Auguest 2021',
    'Techgig',
    'Python',
    true,
    'https://drive.google.com/file/d/1VQabwxaNvgsgj-rLCAvJQyyflXi5MfaJ/view?usp=sharing',
    'assets/Organisations/techgig.png',
  ),
  Certification(
    'April 2018',
    'Spoken Tutorial',
    'Completion of C Training',
    true,
    'https://drive.google.com/file/d/1-Q6cmEj6caPc8nr6USRplA15JgNht3s7/view?usp=sharing',
    'assets/Organisations/spoken-tutorial.jpg',
  ),
  Certification(
    'July 2020',
    'IBM',
    'Python 101 for Data Science',
    true,
    'https://courses.cognitiveclass.ai/certificates/32ee6eeead3e4573a16a3e86e5c856c0',
    'assets/Organisations/ibm.png',
  ),
  Certification(
    'July 2020',
    'Coding ninjas',
    'Interview Jumpstart',
    true,
    'https://drive.google.com/file/d/1B-a7C0qjk8GDo5io8QAT8Rj4xsWDqX7e/view?usp=sharing',
    'assets/Organisations/coding_ninjas.png',
  ),
  Certification(
    'December 2020',
    'Coding Blocks',
    'Python Fundamentals',
    true,
    'https://drive.google.com/file/d/14K9dBErRHDj1UCLdtuiB0JNYrdym1fV9/view?usp=sharing',
    'assets/Organisations/coding_blocks.jpg',
  ),
  Certification(
    'December 2020',
    'Coding Blocks',
    'Interview Preperation (C++)',
    true,
    'https://drive.google.com/file/d/1HiGqGUo3b52RH0HZoZJEnVZ_jht-xIcZ/view?usp=sharing',
    'assets/Organisations/coding_blocks.jpg',
  ),
  Certification(
    'July 2020',
    'Coding Blocks',
    'Competitive Programming Contest Problems',
    true,
    'https://drive.google.com/file/d/1Pn-KDm1iQIs2j5z5Xz6Aatdb3_5JjeUJ/view?usp=sharing',
    'assets/Organisations/coding_blocks.jpg',
  ),
  Certification(
    'August 2020',
    'Coding Blocks',
    'C++ Standard Template Library',
    true,
    'https://drive.google.com/file/d/1iPTAdZCP8-YUBZ8fzLHxUQEBQ4fYw2le/view?usp=sharing',
    'assets/Organisations/coding_blocks.jpg',
  ),
  Certification(
    'December 2020',
    'Coding Blocks',
    'C++ Fundamentals',
    true,
    'https://drive.google.com/file/d/1grDPlFyOPIMiPJX7wOr2E4PjQlS0QThg/view?usp=sharing',
    'assets/Organisations/coding_blocks.jpg',
  ),
  Certification(
    'April 2020',
    'Corona Commando',
    'Corona Commando',
    true,
    'https://drive.google.com/file/d/1cLbpV0NQq5X4ajKadgWi0z3kYIgH9l7R/view?usp=sharing',
    'assets/Organisations/corona_commando.png',
  ),
  Certification(
    'April 2021',
    'Dare2Compete',
    'Dare2Compete Awards 2021',
    true,
    'https://drive.google.com/file/d/1OiMMyyTtOwVJCQoR7AkgNdw5W-ZPw7AD/view?usp=sharing',
    'assets/Organisations/dare2compete.png',
  ),
  Certification(
    'November 2020',
    'Give My Certificate',
    'Corona warrior',
    true,
    'https://verify.givemycertificate.com/verify/6908e329-e254-47c4-97e1-f21486980bb1',
    'assets/Organisations/give-my-certificate.jpg',
  ),
  Certification(
    'June 2021',
    'Forage',
    'Accenture Developer Program',
    true,
    'https://drive.google.com/file/d/1tbA5e1t_n155Pm05tpHEyty_BKIiBBcF/view?usp=sharing',
    'assets/Organisations/forage.png',
  ),
];
